# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  # :tyranno: ${.name}
  name: tyranno

  # A short description of the repository that will show up on GitHub
  # :tyranno: ${.description}
  description:
    Generate beautifully modern Python projects with seamless, GitHub-based CI/CD and loads of integrations.

    # :tyranno: ${.link.main}
  homepage: https://github.com/dmyersturnbull/tyranno

  # :tyranno: topics: ${.keywords~|yaml(@)~}
  topics: [cookiecutter-python, template, pyproject-toml, poetry, conda-build]

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true

  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Adapted from https://opensource.creativecommons.org/contributing-code/repo-labels/
labels:
  - name: "breaking"
    description: "ğŸ”¨ Breaking change"
    color: "#000000"
  - name: "revert"
    description: "ğŸ—‘ Reversion"
    color: "#000000"
  - name: "highlight"
    description: "âœ¨ Highlight"
    color: "#004026"
  - name: "sticky note"
    description: "ğŸ”– Important for reference"
    color: "#ffee00"
  - name: "security"
    description: "ğŸ”’ Security"
    color: "#ffffff"
  - name: "type: test"
    description: "ğŸš¨ Adding missing tests or correcting existing tests"
    color: "#ffffff"
  - name: "type: performance"
    description: "ğŸš€ A code change that improves performance"
    color: "#ffffff"
  - name: "type: feature"
    description: "âœ¨ A new feature"
    color: "#ffffff"
  - name: "type: fix"
    description: "ğŸ› A bug fix"
    color: "#ffffff"
  - name: "type: docs"
    description: "ğŸ“š Documentation only changes"
    color: "#ffffff"
  - name: "type: build"
    description: "ğŸ›  Changes that affect the build system or external dependencies"
    color: "#ffffff"
  - name: "type: question"
    description: "â“ Can be resolved with an answer"
    color: "#f9bbe5"
  - name: "type: discussion"
    description: "ğŸ’¬ Open for discussions and feedback"
    color: "#f9bbe5"
  - name: "priority: critical"
    description: "ğŸŸ¥ Must be fixed ASAP"
    color: "#b60205"
  - name: "priority: high"
    description: "ğŸŸ§ Stalls work on the project or its dependents"
    color: "#ff9f1c"
  - name: "priority: medium"
    description: "ğŸŸ¨ Not blocking but should be fixed soon"
    color: "#ffcc00"
  - name: "ğŸŸ© priority: low"
    description: "Low priority and doesn't need to be rushed"
    color: "#cfda2c"
  - name: "â¬œ priority: none"
    description: "Too minor to fix"
    color: "#ffffff"
  - name: "status: ready for dev"
    description: "ğŸ Ready for work"
    color: "#cccccc"
  - name: "status: blocked"
    description: "ğŸš§ Blocked & therefore not ready for work"
    color: "#999999"
  - name: "status: ticket work required"
    description: "ğŸ§¹ Needs more details before it can be worked on"
    color: "#666666"
  - name: "status: label work required"
    description: "ğŸ”– Needs proper labelling before it can be worked on"
    color: "#666666"
  - name: "status: discarded"
    description: "â›”ï¸ Will not be worked on"
    color: "#eeeeee"
  - name: "status: discontinued"
    description: "ğŸ™… Not suitable for work as repo is in maintenance"
    color: "#eeeeee"
  - name: "status: awaiting triage"
    description: "ğŸš¦ Has not been triaged & therefore, not ready for work"
    color: "#333333"
  - name: "effort: 1"
    description: "1ï¸âƒ£ trivial"
    color: "#400040"
  - name: "effort: 2"
    description: "2ï¸âƒ£ easy"
    color: "#600040"
  - name: "effort: 3"
    description: "3ï¸âƒ£ moderate"
    color: "#800040"
  - name: "effort: 4"
    description: "4ï¸âƒ£ hard"
    color: "#a00040"
  - name: "effort: 5"
    description: "5ï¸âƒ£ severe"
    color: "#c00040"

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions: null
